name: 'Add Badge to README'
description: 'Adds Cypress test result badge to README'
inputs:
  outcome:
    description: 'Test outcome'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Add success badge
      if: inputs.outcome == 'success'
      shell: bash
      run: |
        echo "## RESULTAT DELS ÚLTIMS TESTS" >> README.md
        echo "![Cypress Tests](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)" >> README.md
        
    - name: Add failure badge
      if: inputs.outcome == 'failure'
      shell: bash
      run: |
        echo "## RESULTAT DELS ÚLTIMS TESTS" >> README.md
        echo "![Test Failure](https://img.shields.io/badge/test-failure-red)" >> README.md