name: nodejs-blog-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Run Linter
        run: npm run lint

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start server and run Cypress tests
        continue-on-error: true
        run: |
          # Iniciar servidor en background
          npm start &
          # Esperar a que esté listo
          npx wait-on http://localhost:3000
          # Ejecutar tests
          npx cypress run 2>&1 | tee result.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: result.txt
          retention-days: 1

  add_badge:
    name: Add Test Badge
    runs-on: ubuntu-latest
    needs: cypress
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: cypress-results

      - name: Set outcome from test results
        id: set-outcome
        shell: bash
        run: |
          if grep -q "FAIL" result.txt || grep -q "Error" result.txt; then
            echo "cypress_outcome=failure" >> $GITHUB_OUTPUT
          else
            echo "cypress_outcome=success" >> $GITHUB_OUTPUT
          fi

      - name: Add badge to README
        uses: ./.github/actions/add-badge
        with:
          outcome: ${{ steps.set-outcome.outputs.cypress_outcome }}

      - name: Commit and push badge changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update test result badge [skip ci]" || exit 0
          git push

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  notification:
    name: Send Notification
    runs-on: ubuntu-latest
    needs: [lint, cypress, add_badge, deploy]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set job results
        run: |
          echo "LINTER_RESULT=${{ needs.lint.result }}" >> $GITHUB_ENV
          echo "CYPRESS_RESULT=${{ needs.cypress.result }}" >> $GITHUB_ENV
          echo "ADD_BADGE_RESULT=${{ needs.add_badge.result }}" >> $GITHUB_ENV
          echo "DEPLOY_RESULT=${{ needs.deploy.result }}" >> $GITHUB_ENV

      - name: Print job results
        run: |
          echo "Linter result: $LINTER_RESULT"
          echo "Cypress result: $CYPRESS_RESULT"
          echo "Add badge result: $ADD_BADGE_RESULT"
          echo "Deploy result: $DEPLOY_RESULT"

      - name: Send notification
        uses: ./.github/actions/send-notification
        with:
          email: ${{ secrets.EMAIL }}
          linter_result: $LINTER_RESULT
          cypress_result: $CYPRESS_RESULT
          add_badge_result: $ADD_BADGE_RESULT
          deploy_result: $DEPLOY_RESULT