name: nodejs-blog-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write

jobs:
  linter_job:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm run lint

  cypress_job:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        continue-on-error: true
        run: npm run cypress 2>&1 | tee result.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: result.txt
          retention-days: 1

  add_badge_job:
    name: Add Test Badge
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: cypress-results

      - name: Set outcome from test results
        id: set-outcome
        shell: bash
        run: |
          if grep -q "FAIL" result.txt || grep -q "Error" result.txt; then
            echo "::set-output name=cypress_outcome::failure"
          else
            echo "::set-output name=cypress_outcome::success"
          fi

      - name: Add badge to README
        uses: ./.github/actions/add-badge
        with:
          outcome: ${{ steps.set-outcome.outputs.cypress_outcome }}

      - name: Commit and push badge changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update test result badge" || exit 0
          git push

  deploy_job:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  notification_job:
    name: Send Notification
    runs-on: ubuntu-latest
    needs: [linter_job, cypress_job, add_badge_job, deploy_job]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Send notification
        uses: ./.github/actions/send-notification
        with:
          email: ${{ secrets.EMAIL }}
          linter_result: ${{ needs.linter_job.result }}
          cypress_result: ${{ needs.cypress_job.result }}
          add_badge_result: ${{ needs.add_badge_job.result }}
          deploy_result: ${{ needs.deploy_job.result }}