name: nodejs-blog-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  cypress:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npm run cypress
        continue-on-error: true
      - name: Save Cypress results
        run: echo "All tests passed" > result.txt || echo "Some tests failed" > result.txt
      - name: Upload Cypress results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: result.txt
          retention-days: 30

  add_badge:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Cypress results
        uses: actions/download-artifact@v4
        with:
          name: cypress-results

      - name: Set Cypress outcome
        id: cypress_outcome
        run: |
          result=$(cat result.txt)
          if [[ $result == *"All tests passed"* ]]; then
            echo "::set-output name=cypress_outcome::success"
          else
            echo "::set-output name=cypress_outcome::failure"
          fi

      - name: Add badge to README
        uses: ./.github/actions/add-badge
        with:
          outcome: ${{ steps.cypress_outcome.outputs.cypress_outcome }}

      - name: Commit and push badge
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with Cypress badge" || echo "No changes to commit"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: add_badge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  notify:
    runs-on: ubuntu-latest
    needs: [linter, cypress, add_badge, deploy]
    if: always()
    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: 'Resultado del workflow ejecutado'
          body: |
            S'ha realitzat un push en la branca main que ha provocat l'execució del workflow amb els següents resultats:
            - linter_job: ${{ needs.linter.result }}
            - cypress_job: ${{ needs.cypress.result }}
            - add_badge_job: ${{ needs.add_badge.result }}
            - deploy_job: ${{ needs.deploy.result }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}


  language_metrics:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show language metrics
        uses: GitHub-Linguist/linguist-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
