name: nodejs-blog-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  cypress:
  runs-on: ubuntu-latest
  needs: linter
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Run Cypress tests
      run: npm run cypress
      continue-on-error: true
    - name: Upload Cypress results
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: result.txt
        retention-days: 30


  add_badge:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Cypress results
        uses: actions/download-artifact@v3
        with:
          name: cypress-results
      - name: Set badge status
        id: badge
        run: |
          result=$(cat result.txt)
          if [[ $result == *"All tests passed"* ]]; then
            echo "::set-output name=badge::success"
          else
            echo "::set-output name=badge::failure"
          fi
      - name: Update README with badge
        uses: peter-evans/create-or-update-file@v3
        with:
          path: README.md
          commit-message: 'Update README with Cypress badge'
          content: |
            ![Cypress Badge](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)

  deploy:
    runs-on: ubuntu-latest
    needs: add_badge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Resultado del workflow ejecutado'
          body: |
            S'ha realitzat un push en la branca main que ha provocat l'execució del workflow amb els següents resultats:
            - linter_job: ${{ needs.linter.outcome }}
            - cypress_job: ${{ needs.cypress.outcome }}
            - add_badge_job: ${{ needs.add_badge.outcome }}
            - deploy_job: ${{ needs.deploy.outcome }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}

  language_metrics:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display language metrics
        uses: GitHub-Linguist/linguist-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
